name: flutter_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bitsdojo_window: ^0.1.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  objectbox: ^4.1.0
  objectbox_flutter_libs: any
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/